name: Coq Verification

on:
  push:
  pull_request:

jobs:
  check-coq:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Coq
        run: |
          sudo apt-get update -y -q
          sudo apt-get install -y -q --no-install-recommends coq

      - name: Compile Coq files
        run: |
          coq_makefile -f _CoqProject -o Makefile
          make
